//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 PcManagerClient.rc 使用
//
#define IDD_MAIN_INTERFACE_DLG          102
#define IDR_MAINFRAME                   128
#define IDD_KILL_VIRUS_DLG              130
#define IDD_CCLEANER_DLG                132
#define IDD_PROCESS_DLG                 134
#define IDD_FILE_DLG                    136
#define IDD_SOFTWARE_DLG                138
#define IDD_TOOLS_DLG                   140
#define IDD_PE_DATA_DIRECTORY_TABLE     141
#define IDD_PE_MAIN_MENU                142
#define IDD_PE_SECTIONS_TABLE           143
#define IDD_PE_EXPORT_TABLE             144
#define IDD_PE_IMPORT_TABLE             146
#define IDC_TAB_MAIN_INTERFACE          1000
#define IDC_BTN_OPEN_PE_FILE            1001
#define IDC_EDIT_DOS_Magic              1002
#define IDC_EDIT_DOS_Fanew              1003
#define IDC_EDIT_NT_Signature           1004
#define IDC_EDIT_FILE_Machine           1005
#define IDC_EDIT_FILE_NumberOfSections  1006
#define IDC_EDIT_FILE_SizeOfOptionalHeader 1007
#define IDC_EDIT_FILE_Characteristics   1008
#define IDC_EDIT_OPTIONAL_Magic         1009
#define IDC_EDIT_OPTIONAL_AddressOfEntryPoint 1010
#define IDC_BTN_CLOSE_PROCESS           1011
#define IDC_EDIT_OPTIONAL_ImageBase     1012
#define IDC_EDIT_OPTIONAL_SectionAligment 1013
#define IDC_EDIT_OPTIONAL_FileAlignment 1014
#define IDC_EDIT_OPTIONAL_SizeOfImage   1015
#define IDC_EDIT_OPTIONAL_SizeOfHeaders 1016
#define IDC_EDIT_OPTIONAL_Subsystem     1017
#define IDC_EDIT_OPTIONAL_DllCharacteristics 1018
#define IDC_EDIT_OPTIONAL_NumberOfRvaAndSizes 1019
#define IDC_BTN_OPEN_SECTIONS           1020
#define IDC_LIST_SECTION_INFO           1021
#define IDC_BTN_OPEN_DATA_DIRECTORY     1022
#define IDC_EDIT_NT_OPTIONAL_EXPORT_RVA 1023
#define IDC_EDIT_NT_OPTIONAL_EXPORT_SIZE 1024
#define IDC_EDIT_NT_OPTIONAL_IMPORT_RVA 1025
#define IDC_EDIT_NT_OPTIONAL_IMPORT_SIZE 1026
#define IDC_EDIT_NT_OPTIONAL_RESOURCE_RVA 1027
#define IDC_EDIT_NT_OPTIONAL_RESOURCE_SIZE 1028
#define IDC_EDIT_NT_OPTIONAL_EXCEPTION_RVA 1029
#define IDC_EDIT_NT_OPTIONAL_EXCEPTION_SIZE 1030
#define IDC_BTN_NT_OPTIONAL_EXPORT      1031
#define IDC_EDIT_NT_OPTIONAL_SECURITY_RVA 1039
#define IDC_EDIT_NT_OPTIONAL_SECURITY_SIZE 1040
#define IDC_EDIT_NT_OPTIONAL_BASERELOC_RVA 1041
#define IDC_EDIT_NT_OPTIONAL_BASERELOC_SIZE 1042
#define IDC_EDIT_NT_OPTIONAL_DEBUG_RVA  1043
#define IDC_EDIT_NT_OPTIONAL_DEBUG_SIZE 1044
#define IDC_EDIT_NT_OPTIONAL_ARCHITECTURE_RVA 1045
#define IDC_EDIT_NT_OPTIONAL_ARCHITECTURE_SIZE 1046
#define IDC_EDIT_NT_OPTIONAL_GLOBALPTR_RVA 1077
#define IDC_EDIT_NT_OPTIONAL_GLOBALPTR_SIZE 1078
#define IDC_EDIT_NT_OPTIONAL_TLS_RVA    1079
#define IDC_EDIT_NT_OPTIONAL_TLS_SIZE   1080
#define IDC_EDIT_NT_OPTIONAL_CONFIG_RVA 1081
#define IDC_EDIT_NT_OPTIONAL_CONFIG_SIZE 1082
#define IDC_EDIT_NT_OPTIONAL_BOUND_IMPORT_RVA 1083
#define IDC_EDIT_NT_OPTIONAL_BOUND_IMPORT_SIZE 1084
#define IDC_EDIT_NT_OPTIONAL_IAT_RVA    1085
#define IDC_EDIT_NT_OPTIONAL_IAT_SIZE   1086
#define IDC_EDIT_NT_OPTIONAL_DELAY_IMPORT_RVA 1087
#define IDC_EDIT_NT_OPTIONAL_DELAY_IMPORT_SIZE 1088
#define IDC_EDIT_NT_OPTIONAL_COM_DESCRIPTOR_RVA 1089
#define IDC_EDIT_NT_OPTIONAL_COM_DESCRIPTOR_SIZE 1090
#define IDC_BTN_NT_OPTIONAL_RESOURCE    1091
#define IDC_BTN_NT_OPTIONAL_IMPORT      1092
#define IDC_BTN_NT_OPTIONAL_EXCEPTION   1093
#define IDC_BTN_NT_OPTIONAL_BASERELOC   1094
#define IDC_BTN_NT_OPTIONAL_SECURITY    1095
#define IDC_BTN_NT_OPTIONAL_DEBUG       1096
#define IDC_BTN_NT_OPTIONAL_GLOBALPTR   1097
#define IDC_BTN_NT_OPTIONAL_ARCHITECTURE 1098
#define IDC_BTN_NT_OPTIONAL_TLS         1099
#define IDC_BTN_NT_OPTIONAL_BOUND_IMPORT 1100
#define IDC_BTN_NT_OPTIONAL_CONFIG      1101
#define IDC_BTN_NT_OPTIONAL_IAT         1102
#define IDC_BTN_NT_OPTIONAL_COM_DESCRIPTOR 1103
#define IDC_BTN_NT_OPTIONAL_DELAY_IMPORT 1104
#define IDC_LIST_EXPORT_TABLE           1105
#define IDC_EDIT_DATA_EXPORT_NAME       1106
#define IDC_EDIT_DATA_EXPORT_FUN_NAME_NUM 1107
#define IDC_EDIT_DATA_EXPORT_FUN_NUM    1108
#define IDC_LIST_IMPORT_MODULE          1109
#define IDC_LIST_IMPORT_FUNTION         1110
#define IDC_LIST_PROCESS_INFO           1111
#define IDC_LIST_THREAD_INFO            1112
#define IDC_LIST_PROCESS_MODULE_INFO    1113
#define IDC_BTN_CLOSE_THREAD            1114
#define IDC_BTN_REFRESH_PROCESS         1115

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
